# Generated by Django 4.2 on 2024-08-18 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_bal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('budget_amt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_monthly_bal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=7)),
                ('current_bal', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('org', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('inserted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking.expensetype')),
            ],
        ),
    ]
