# Generated by Django 4.0.2 on 2022-02-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
