# Generated by Django 4.2 on 2024-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking', '0002_rename_expense_budget_expense_amt_budget_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_amt',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='current_bal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='expense_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_monthly_bal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
