# Generated by Django 4.2 on 2024-08-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking', '0004_rename_item_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
