# Generated by Django 4.2.5 on 2024-11-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking', '0005_alter_budget_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
